language: node_js
node_js:
  - "8.11.3"

install:
  - npm install
  - npm run lerna:lint
  - npm run lerna:test

deploy:
  skip_cleanup: true
  provider: script
  script: npm run publish:ci
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master && $TRAVIS_EVENT_TYPE == pull_request"

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $githubpagestoken  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: develop
